// flow-typed signature: 3d7285dcaaf36220a4e2a7a01ca47664
// flow-typed version: <<STUB>>/waait_v^1.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'waait'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'waait' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'waait/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'waait/index' {
  declare module.exports: $Exports<'waait'>;
}
declare module 'waait/index.js' {
  declare module.exports: $Exports<'waait'>;
}
declare module 'waait/test.js' {
  declare module.exports: $Exports<'waait/test'>;
}
